#!/usr/bin/env bash
# A bash script that displays To infinity and beyond indefinitely.
# In between each iteration of the loop, add a sleep 2

while true
    echo "To infinity and beyond"
    sleep 2
